version: '3.4'
services:
  ffc-demo-user-service:
    ports:
      - "3002:3002"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  ffc-demo-user-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
