version: '3.7'

# This file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-user-service:
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate && npm run test"
    environment:
      NODE_ENV: test
