version: '3.4'
services:
  ffc-demo-user-service:
    build: .
    image: ffc-demo-user-service
    container_name: ffc-demo-user-service
    command: sh -c "npm run start:watch"
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PORT: 5432

