version: '3'
services:
  mine-support-user-service:
    build: .
    image: mine-support-user-service
    container_name: mine-support-user-service
    environment:
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - mine-support
      - mine-support-users
    ports:
      - "3002:3002"

  mine-support-postgres-users:
    container_name: mine-support-postgres-users
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: mine_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - mine-support-users

networks:
  mine-support:
    external: true
  mine-support-users: {}
