version: '3.4'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-user-service:
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate && npm run test"
    volumes:
      - ./test-output:/usr/src/app/test-output
