version: '3.7'
services:
  ffc-demo-user-service:
    build: 
      context: .
      target: production
    image: ffc-demo-user-service
    depends_on:
      - ffc-demo-user-postgres
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-user-postgres
      POSTGRES_PORT: 5432
    networks:
      - ffc-demo-users
    volumes:
      - ./server/:/usr/src/app/server/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json

  ffc-demo-user-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - ffc-demo-users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules: {}
  postgres_data: {}

networks:
  ffc-demo-users: {}
