version: '3.7'

# This override file should be used when running the migrations
# to configure the database

services:
  ffc-demo-user-service:
    build: 
      context: .
      target: development
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate"

