version: '3.4'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  mine-support-user-service:
    networks:
      - mine-support

networks:
  mine-support:
   external: true
