version: '3.4'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-user-service:
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate && npm run test"
    depends_on:
      - ffc-demo-user-postgres
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-user-postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./test-output:/usr/src/app/test-output

  ffc-demo-user-postgres:
    container_name: ffc-demo-user-postgres
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data:
