version: '3.7'

# This override file should be used in development environments to
# link this service to sibling services from other repositories

services:
  ffc-demo-user-service:
    ports:
      - "3002:3002"
    networks:
      - ffc-demo

networks:
  ffc-demo:
   external: true
