version: '3.4'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-user-service:
    depends_on:
      - ffc-demo-user-postgres
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate && npm run start:watch"
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-user-postgres
      POSTGRES_PORT: 5432
    networks:
      - ffc-demo-users

  ffc-demo-user-postgres:
    container_name: ffc-demo-user-postgres
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    networks:
      - ffc-demo-users
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  user_postgres_data: {}
  node_modules: {}

networks:
  ffc-demo:
    external: true
  ffc-demo-users: {}
