version: '3.4'
services:
  ffc-demo-user-service:
    build: .
    image: ffc-demo-user-service
    command: sh -c "scripts/wait-for/wait-for ffc-demo-user-postgres:5432 -- npm run migrate && npm run start:watch"
    depends_on:
      - ffc-demo-user-postgres
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: ffc-demo-user-postgres
      POSTGRES_PORT: 5432
    networks:
      - ffc-demo-users
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  ffc-demo-user-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_users
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - ffc-demo-users

volumes:
  node_modules: {}

networks:
  ffc-demo-users: {}
