version: '3.4'

# This override file should be used in development environments to
# link this service to sibling services from other repositories

services:
  ffc-demo-user-service:
    ports:
      - "3002:3002"
    networks:
      - ffc-demo
  ffc-demo-user-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  ffc-demo:
   external: true

volumes:
  postgres_data: {}
