kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}
spec:
  type: ExternalName
  externalName: {{ .Values.database.externalName }}
  ports:
    - name: port
      port: {{ .Values.database.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
