#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

(
  cd "${projectRoot}"

  echo "Deploying user PostgreSQL"
  helm upgrade \
    --atomic \
    --install \
    --namespace mine-support-user-service \
    --set persistence.enabled=false \
    --set postgresqlDatabase=mine_users \
    --set postgresqlPassword=changeme \
    --set postgresqlUsername=postgres@mine-support2 \
    --set service.port=5432 \
    --wait \
    mine-support-user-postgres \
    stable/postgresql

  echo "Deploying user service"
  helm upgrade \
    --atomic \
    --install \
    --namespace mine-support-user-service \
    --wait \
    mine-support-user-service \
    ./helm
)
