#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set Docker/Kubernetes resource names managed by this script
dockerPrefix="ffc-demo-user"
kubernetesNamespace="ffc-demo"
serviceName="ffc-demo-user-service"

(
  cd "${projectRoot}"

  echo "Deploying PostgreSQL."
  helm upgrade \
    --atomic \
    --install \
    --namespace ${kubernetesNamespace} \
    --values helm/${serviceName}/postgres-values.yaml \
    --wait \
    ${dockerPrefix}-postgres \
    stable/postgresql

  echo "Migrating database."
  kubectl apply \
    -f scripts/helm/development-jobs/migrate.yaml \
    --namespace ${kubernetesNamespace}

  echo "Deploying service."
  helm upgrade \
    --atomic \
    --install \
    --namespace ${kubernetesNamespace} \
    --values helm/${serviceName}/development-values.yaml \
    --wait \
    ${serviceName} \
    ./helm/${serviceName}
)
