{{- define "ffc-demo-user-service.container" -}}
name: {{ quote .Values.name }}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: POSTGRES_USERNAME
  value: {{ quote .Values.postgresUsername }}
- name: POSTGRES_PASSWORD
  value: {{ quote .Values.postgresPassword }}
- name: POSTGRES_DB
  value: {{ quote .Values.postgresDatabase }}
- name: POSTGRES_HOST
  value: {{ quote .Values.postgresHost }}
- name: POSTGRES_PORT
  value: {{ quote .Values.postgresPort }}
- name: PORT
  value: {{ quote .Values.container.port }}
ports:
- containerPort: {{ .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
{{- end -}}
