{{- define "ffc-demo-user-service.init-container" -}}
name:  "{{ .Values.name }}-migrate"
image: {{ quote .Values.image }}
command: ['npm', 'run', 'migrate']
env:
- name: POSTGRES_USERNAME
  value: {{ quote .Values.postgresService.postgresUsername }}
- name: POSTGRES_PASSWORD
  value: {{ quote .Values.postgresService.postgresPassword }}
- name: POSTGRES_DB
  value: {{ quote .Values.postgresService.postgresDatabase }}
- name: POSTGRES_HOST
  value: {{ quote .Values.postgresService.postgresHost }}
- name: POSTGRES_PORT
  value: {{ quote .Values.postgresService.postgresPort }}
{{- end -}}
