{{- include "ffc-helm-library.deployment" (list . "ffc-demo-user-service.deployment") -}}
{{- define "ffc-demo-user-service.deployment" -}}
spec:
  template:
    spec:
      initContainers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-user-service.init-container") }}
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-user-service.container") }}
{{- end -}}
