apiVersion: v1
kind: Service
metadata:
  labels:
    app.component: mine-support-user-service
  name: mine-support-user-service
spec:
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app.component: mine-support-user-service
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: mine-support-user-service
  name: mine-support-user-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.component: mine-support-user-service
    spec:
      containers:   
      - name: mine-support-user-service
        image: mine-support-user-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3002               
      restartPolicy: Always
status: {}
