#!/usr/bin/env sh

## Exec script
## Execute a given command in the ffc-demo-user-service container.
## If the service container is not running, this script will start and
## stop it either side of running the command.

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"

  existingService="$( docker ps -q --filter name=^ffc-demo-user-service$ )"
  existingVolumes="$( docker volume ls --filter name=^ffc-demo-user-service --format={{.Name}} )"

  if [ -z "${existingService}" ]; then
    printf "\nCreating service to execute command in.\n"
    docker-compose up --detach
  fi

  printf "\nExecuting command in ffc-demo-user-service:\n"
  echo "$@"

  docker-compose exec ffc-demo-user-service $@

  printf "\nCommand completed.\n"

  if [ -z "${existingService}" ]; then
    if [ -z "${existingVolumes}" ]; then
      printf "\nRemoving created service and volumes.\n"
      docker-compose down --volumes
    else
      printf "\nRemoving created service (leaving volumes as some existed already).\n"
      docker-compose down
    fi
  fi
)
