#!/bin/sh
docker-compose down -v
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml build --no-cache mine-support-user-service
docker-compose -f docker-compose.yaml -f docker-compose.migrate.yaml up --force-recreate mine-support-user-service
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml up mine-support-user-service

