#!/bin/bash

docker network inspect mine-support &>/dev/null || docker network create mine-support

docker-compose down -v
docker-compose build --no-cache mine-support-user-service
docker-compose up --force-recreate mine-support-user-service
