#!/bin/sh
docker network inspect mine-support &>/dev/null || docker network create mine-support
docker-compose down -v
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml build --no-cache
docker-compose -f docker-compose.yaml -f docker-compose.migrate.yaml up --force-recreate
docker-compose -f docker-compose.yaml -f docker-compose.local.yaml up
