#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"

  docker-compose \
    -f docker-compose.yaml \
    -f docker-compose.test.yaml \
    run mine-support-user-service \
    sh -c "npx wait-on -v tcp:mine-support-user-postgres:5432 && npm run migrate && npm run test"

  docker-compose down -v
)
