#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

compose() {
  (cd "${projectRoot}" && docker-compose -f docker-compose.yaml -f docker-compose.test.yaml $@)
}

(
  cd "${projectRoot}"

  # Guarantee clean environment
  compose down --volumes

  # Run tests
  compose run ffc-demo-user-service

  # Clean up
  compose down --volumes
)
