environment: development
name: ffc-demo-user-service
image: ffc-demo-user-service
imagePullSecret:
postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_users
postgresHost: ffc-demo-user-postgres
postgresServiceName: ffc-demo-user-postgres
postgresExternalName: host.docker.internal
postgresPort: 5432
service:
  type: ClusterIP
  port: 80
container:
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  command: ["/bin/sh", "-c"]
  args: ["npm --no-update-notifier run migrate; node index"]
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 3
livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 3
