environment: development
name: mine-support-user-service
image: mine-support-user-service
postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_users
postgresHost: mine-support-user-postgres-postgresql
postgresExternalName: host.docker.internal
postgresExternalServiceName: mine-support-user-postgres
postgresPort: 5432
service:
  type: ClusterIP
  port: 80
container:
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  command: ["/bin/sh", "-c"]
  args: ["scripts/wait-for/wait-for $(POSTGRES_HOST):5432 -- npm --no-update-notifier run migrate && node index"]
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
